#!/bin/bash

# テストブランチ
test_branch="test"

while read local_ref local_sha remote_ref remote_sha
do
    # プッシュ先ブランチがテストブランチからの派生である場合...
    if [[ "$local_ref" =~ ^refs/heads/$test_branch/ ]]; then
        cat <<-EOS
        --------------------------------------------------

        DO NOT PUSH NEW BRANCHES DERIVED FROM $test_branch!

        --------------------------------------------------
EOS
        exit 1
    fi
done

exit 0